### PR TITLE
Minor colors update for the main theme + Major update for Python

### PR DESCRIPTION
**Pull request by maxshapira9**
Hey,

Your theme is a work of art. Can't thank you enough for your excellent work. Well done!

I've made minor changes for the main theme colors and added a major update for Python colors. 

Hope you'll like it.

Thanks,
Max

### CODE REVIEW

**Comment by shaodahong** [comment]
Thanks. this is an awesome change, but I leave some suggestions

## Indistinguishable ignore file

### Before

image


### After

image

**Comment by shaodahong** [comment]
# Side text color a bit dark

## Before
image


## After
image

**Comment by maxshapira9** [comment]
@shaodahong Looks good. I prefer the side text color a bit dark because it's less distracting and I can focus on the primary code (my OCD).

**Comment by shaodahong** [comment]
ok, but we can distinguish ignore file color?

**Comment by maxshapira9** [comment]
@shaodahong Sure.

**Comment by shaodahong** [comment]
It's done? I maybe publish in this week

**Comment by maxshapira9** [comment]
@shaodahong Now it's done. Thanks.

**Comment by shaodahong** [comment]
Thanks.

**Pull request merged**
